use_frameworks!

platform :ios, '9.0'

target 'SwiftyTextEncoding_Example' do
  pod 'SwiftyTextEncoding', :path => '../'

  target 'SwiftyTextEncoding_Tests' do
    inherit! :search_paths

    
  end
end
